### ISSUE TITLE
Missing files in the pip installation

### ISSUE THREAD

**Issue by ridha-mm** [youngsm/grbLC#2]
* Operating System: In both Linux and Windows

### Description

This file is not included in the python package though it is present in the repository
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/grblc/convert/SF11_conversions.txt'`

I have to manually copy the missing file from the repository into my local directory.

**Comment by youngsm** [comment]
Fixed in #4.
